### ISSUE TITLE
Dask Throws Exception Once in a While due to `gamma` import

### ISSUE THREAD

**Issue by 2gotgrossman** [insarlab/PySAR#31]
This Exception used to be thrown once in a while when running with Dask, but now it is thrown consistently (the last 4 times I have run the code with Dask).

@yunjunz , you mentioned that we could just add the `gamma` function to our code and that would solve the problem. Is that still possible? 

```
Traceback (most recent call last):
  File "pysar/ifgram_inversion.py", line 1220, in <module>
    main()
  File "pysar/ifgram_inversion.py", line 1211, in main
    ifgram_inversion(inps.ifgramStackFile, inps)
  File "pysar/ifgram_inversion.py", line 1117, in ifgram_inversion
    for future, result in as_completed(futures, with_results=True):
  File "/nethome/dwg11/anaconda2/envs/pysar_new/lib/python3.6/site-packages/distributed/client.py", line 3858, in __next__
    return self._get_and_raise()
  File "/nethome/dwg11/anaconda2/envs/pysar_new/lib/python3.6/site-packages/distributed/client.py", line 3849, in _get_and_raise
    six.reraise(*result)
  File "/nethome/dwg11/anaconda2/envs/pysar_new/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/nethome/dwg11/anaconda2/envs/pysar_new/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/nethome/dwg11/anaconda2/envs/pysar_new/lib/python3.6/site-packages/numpy/core/__init__.py", line 149, in _ufunc_reconstruct
    return getattr(mod, name)
AttributeError: module '__mp_main__' has no attribute 'gamma'
```

**Comment by 2gotgrossman** [comment]
This actually seems pretty hard because it looks like `scipy.special` implements `gamma` using Fortran or C code. However, there is a `math.gamma(x: float)` function. It throws an error when you get `float('inf')`, but I wrote a quick wrapper as a workaround. It runs really quickly on values and is correct within 1E-12. However, I need to test to see how it would work on vectorized implementations.

Here is the function + test code:
```
import math
import scipy.special
from numpy import arange
import time

def gamma(x):
    try:
        return math.gamma(x)
    except ValueError:
        return float('inf')

def test_correctness():
    for i in arange(-10, 10, .01):
        if gamma(i) != scipy.special.gamma(i):
            print(i, gamma(i)- scipy.special.gamma(i))

def test_speed():
    start = time.time()
    for i in arange(-10, 10, .01):
        gamma(i)
    print("Our gamma time: ", time.time() - start)

    start = time.time()
    for i in arange(-10, 10, .01):
        scipy.special.gamma(i)
    print("scipy gamma time: ", time.time() - start)

test_correctness()
test_speed()
```

**Comment by yunjunz** [comment]
@2gotgrossman Your solution looks good to me. The input of `gamma()` is usually small in our cases: < 2000, so the difference between `math.gamma()` and `scipy.special.gamma()` is definitely negligible for us.
