### ISSUE TITLE
minimum version of disk_jobqueue that contains LSFCluster

### ISSUE THREAD

**Issue by yunjunz** [insarlab/PySAR#36]
Hi @2gotgrossman, could you add a minimum version constarint in `docs/conda.txt` file for `dask_jobqueue`, both I and @mirzaees encountered the issue that conda install an obsolete version of 0.1, which does not have LSFCluster. I fixed the issue by re-installed a new miniconda3, which later on install the dask_jobqueue with version 0.4.

https://github.com/insarlab/PySAR/blob/d3cac2b0d4c4e97b01a5fb637c5382f43bcf023d/docs/conda.txt#L4

**Comment by mirzaees** [comment]
@2gotgrossman @yunjunz 
I installed the dask_jobqueue=0.4 but then I get following error which askes for dask distributed. I follow the instruction but nothing changes:


2019-04-15 09:46:31,186 - INFO - pysarApp.py /nethome/sxm1611/insarlab/infiles/sxm1611/TEMPLATES/test_unittestGalapagosSenDT128.template --end load_data |& tee out_pysar.log
20190415:094631 * pysarApp.py /nethome/sxm1611/insarlab/infiles/sxm1611/TEMPLATES/test_unittestGalapagosSenDT128.template --end load_data |& tee out_pysar.log
Traceback (most recent call last):
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/dask/distributed.py", line 5, in <module>
    from distributed import *
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/distributed/__init__.py", line 5, in <module>
    from .actor import Actor, ActorFuture
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/distributed/actor.py", line 4, in <module>
    from .client import Future, default_client
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 29, in <module>
    from dask.optimization import SubgraphCallable
ImportError: cannot import name 'SubgraphCallable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nethome/sxm1611/test/testsara/rsmas_insar/sources/PySAR/pysar/pysarApp.py", line 21, in <module>
    import pysar.workflow  #dynamic import for modules used by pysarApp workflow
  File "/nethome/sxm1611/test/testsara/rsmas_insar/sources/PySAR/pysar/workflow/__init__.py", line 36, in <module>
    importlib.import_module(root_module + '.' + module)
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nethome/sxm1611/test/testsara/rsmas_insar/sources/PySAR/pysar/ifgram_inversion.py", line 24, in <module>
    from dask.distributed import Client, as_completed
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/dask/distributed.py", line 11, in <module>
    raise ImportError(msg)
ImportError: Dask's distributed scheduler is not installed.

Please either conda or pip install dask distributed:

  conda install dask distributed          # either conda install
  pip install dask distributed --upgrade  # or pip install
2019-04-15 09:46:33,222 - INFO - pysarApp.py /nethome/sxm1611/insarlab/infiles/sxm1611/TEMPLATES/test_unittestGalapagosSenDT128.template
20190415:094633 * pysarApp.py /nethome/sxm1611/insarlab/infiles/sxm1611/TEMPLATES/test_unittestGalapagosSenDT128.template
20190415:094633 * (pysarApp.py /nethome/sxm1611/insarlab/infiles/sxm1611/TEMPLATES/test_unittestGalapagosSenDT128.template | tee out_pysar.o) 3>&1 1>&2 2>&3 | tee out_pysar.e
Traceback (most recent call last):
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/dask/distributed.py", line 5, in <module>
    from distributed import *
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/distributed/__init__.py", line 5, in <module>
    from .actor import Actor, ActorFuture
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/distributed/actor.py", line 4, in <module>
    from .client import Future, default_client
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 29, in <module>
    from dask.optimization import SubgraphCallable
ImportError: cannot import name 'SubgraphCallable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nethome/sxm1611/test/testsara/rsmas_insar/sources/PySAR/pysar/pysarApp.py", line 21, in <module>
    import pysar.workflow  #dynamic import for modules used by pysarApp workflow
  File "/nethome/sxm1611/test/testsara/rsmas_insar/sources/PySAR/pysar/workflow/__init__.py", line 36, in <module>
    importlib.import_module(root_module + '.' + module)
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nethome/sxm1611/test/testsara/rsmas_insar/sources/PySAR/pysar/ifgram_inversion.py", line 24, in <module>
    from dask.distributed import Client, as_completed
  File "/nethome/sxm1611/test/testsara/rsmas_insar/3rdparty/miniconda3/lib/python3.6/site-packages/dask/distributed.py", line 11, in <module>
    raise ImportError(msg)
ImportError: Dask's distributed scheduler is not installed.

Please either conda or pip install dask distributed:

  conda install dask distributed          # either conda install
  pip install dask distributed --upgrade  # or pip install
